"""Changing table layout

Revision ID: 66671d031413
Revises: aa80cdd78d2b
Create Date: 2024-09-14 13:33:44.083968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66671d031413'
down_revision = 'aa80cdd78d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_specific_table')
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.drop_index('ix_core_table_name')

    op.drop_table('core_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.create_index('ix_core_table_name', ['name'], unique=False)

    op.create_table('user_specific_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('core_id', sa.INTEGER(), nullable=True),
    sa.Column('user_data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['core_id'], ['core_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employee')
    op.drop_table('project')
    op.drop_table('department')
    # ### end Alembic commands ###
