"""adding common fields to core for example purpose

Revision ID: 7d9333600c5f
Revises: ca3106ea7335
Create Date: 2024-09-16 12:03:19.188469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9333600c5f'
down_revision = 'ca3106ea7335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_field1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('common_field2', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.drop_column('common_field2')
        batch_op.drop_column('common_field1')

    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('position', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
