"""Initial Migration

Revision ID: aa80cdd78d2b
Revises: 
Create Date: 2024-09-14 13:21:24.379818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa80cdd78d2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_table_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('accessible_tables', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('user_specific_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=True),
    sa.Column('user_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['core_id'], ['core_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_specific_table')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('core_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_table_name'))

    op.drop_table('core_table')
    # ### end Alembic commands ###
