"""Update with core tables

Revision ID: ca3106ea7335
Revises: a26d4a2b0435
Create Date: 2024-09-16 11:45:21.730577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3106ea7335'
down_revision = 'a26d4a2b0435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.create_table('core_table_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['core_id'], ['core_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('departments')
    op.drop_table('employees')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('position', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('head', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('core_table_association')
    op.drop_table('core_table')
    # ### end Alembic commands ###
